spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://avnadmin:AVNS_NXqgthmJhr-lAX4GZsL@burcu-hilal-burcu-hilal.j.aivencloud.com:14938/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_NXqgthmJhr-lAX4GZsL
  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes
security:
  jwt:
    secret-key: eQNYL3vKhPv7Pk8GchaJgZU5r6yaWRrjDv76rBECPDL6drqGok5mi2T4Pt7WRf3Aa
    expiration-time: 3600000
