spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret-key: eQNYL3vKhPv7Pk8GchaJgZU5r6yaWRrjDv76rBECPDL6drqGok5mi2T4Pt7WRf3A
    expiration-time: 3600000